questionsList = [
    {
        'text': 'Do you live in a city?',
        'kind': 'YN',
        'plot_type': 'P',
        'category': 'Lo',
        'context': None,
    },
    {
        'text': 'Please state the name of the city in which you live or the name of your nearest city.',
        'kind': 'OP',
        'plot_type': 'M',
        'category': 'Lo',
        'context': None,
    },
    {
        'text': 'Approximately how long (in years) have you lived in your local area?',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'Lo',
        'context': None,
    },
    {
        'text': 'Offers a good way to escape from my troubles.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'PE',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statement. My contribution to Zooniverse projects:',
    },
    {
        'text': 'Makes me feel less lonely.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'PE',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statement. My contribution to Zooniverse projects:',
    },
    {
        'text': 'Makes me feel less guilty about doing enough to support worthwhile causes.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'PE',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statement. My contribution to Zooniverse projects:',
    },
    {
        'text': 'Allows me to support a cause I consider to be important.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'Va',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statement. My contribution to Zooniverse projects:',
    },
    {
        'text': 'Helps me make new contacts that might help my business or career.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'Ca',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statement. My contribution to Zooniverse projects:',
    },
    {
        'text': 'Allows me to explore different career options.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'Ca',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statement. My contribution to Zooniverse projects:',
    },
    {
        'text': 'Lets me learn through direct, hands-on experience of scientific research',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'Un',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statement. My contribution to Zooniverse projects:',
    },
    {
        'text': 'Increases my self-esteem.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'PE',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statement. My contribution to Zooniverse projects:',
    },
    {
        'text': 'Makes me feel better about myself.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'PE',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statement. My contribution to Zooniverse projects:',
    },
    {
        'text': 'Makes me feel needed.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'PE',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statement. My contribution to Zooniverse projects:',
    },
    {
        'text': 'Feels like leisure.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'WL',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statement. My contribution to Zooniverse projects:',
    },
    {
        'text': 'Others with whom I am close place a high value on Zooniverse projects.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'So',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statements.',
    },
    {
        'text': 'My friends contribute to Zooniverse projects.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'So',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statements.',
    },
    {
        'text': 'People I know share an interest in Zooniverse projects.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'So',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statements.',
    },
    {
        'text': 'I feel the Zooniverse allows me to gain a new perspective on scientific research.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'Un',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statements.',
    },
    {
        'text': 'Zooniverse projects help me learn about science.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'Un',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statements.',
    },
    {
        'text': 'I feel as if I am in competition with other Zooniverse users.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'RC',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statements.',
    },
    {
        'text': 'Participating in Zooniverse projects will help me to succeed in my chosen profession.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'Ca',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statements.',
    },
    {
        'text': "I need to feel that I am 'pulling my weight' when undertaking a group task.",
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'RC',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statements.',
    },
    {
        'text': 'It is important that I contribute more classifications to Zooniverse projects than most other users.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'RC',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statements.',
    },
    {
        'text': 'It is important to have access to information that allows the comparison of contributions between Zooniverse users.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'RC',
        'context': 'Thinking about your motivation for participating in Zooniverse projects, please indicate the extent to which you agree with the following statements.',
    },
    {
        'text': 'I feel comfortable around people.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'So',
        'context': 'Please indicate the extent to which you agree with the following statements.'
    },
    {
        'text': 'I am skilled at handling social situations.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'So',
        'context': 'Please indicate the extent to which you agree with the following statements.'
    },
    {
        'text': 'I make friends easily.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'So',
        'context': 'Please indicate the extent to which you agree with the following statements.'
    },
    {
        'text': 'Scientific research is adequately funded through government taxation.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'Va',
        'context': 'Please indicate the extent to which you agree with the following statements.'
    },
    {
        'text': 'All of society benefits from scientific research.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'Va',
        'context': 'Please indicate the extent to which you agree with the following statements.'
    },
    {
        'text': 'The best way to handle people is to tell them what they want to hear.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'Co',
        'context': 'Please indicate the extent to which you agree with the following statements.'
    },
    {
        'text': "People generally don't work hard unless they are forced to.",
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'Co',
        'context': 'Please indicate the extent to which you agree with the following statements.'
    },
    {
        'text': 'It is better that a hundred criminals go free than one innocent person should be unjustly punished.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'Co',
        'context': 'Please indicate the extent to which you agree with the following statements.'
    },
    {
        'text': 'Participating in Zooniverse projects feels like work.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'WL',
        'context': 'Please indicate the extent to which you agree with the following statements.'
    },
    {
        'text': 'I have fun participating in Zooniverse projects.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'WL',
        'context': 'Please indicate the extent to which you agree with the following statements.'
    },
    {
        'text': '1,000 people contributed',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'RC',
        'context': 'Over a million people have registered accounts and contributed to Zooniverse projects. Would you spend more or less time classifying for Zooniverse projects if:'
    },
    {
        'text': '10,000 people contributed',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'RC',
        'context': 'Over a million people have registered accounts and contributed to Zooniverse projects. Would you spend more or less time classifying for Zooniverse projects if:'
    },
    {
        'text': '100,000 people contributed',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'RC',
        'context': 'Over a million people have registered accounts and contributed to Zooniverse projects. Would you spend more or less time classifying for Zooniverse projects if:'
    },
    {
        'text': '10 million people contributed',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'RC',
        'context': 'Over a million people have registered accounts and contributed to Zooniverse projects. Would you spend more or less time classifying for Zooniverse projects if:'
    },
    {
        'text': '100 million people contributed',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'RC',
        'context': 'Over a million people have registered accounts and contributed to Zooniverse projects. Would you spend more or less time classifying for Zooniverse projects if:'
    },
    {
        'text': 'There are several people offline I trust to help solve my problems.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your offline interactions?'
    },
    {
        'text': 'There is someone offline I can turn to for advice about making very important decisions.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your offline interactions?'
    },
    {
        'text': 'If I needed an emergency loan of $500, I know someone offline I could turn to.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your offline interactions?'
    },
    {
        'text': 'The people I interact with offline would put their reputation on the line for me.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your offline interactions?'
    },
    {
        'text': 'The people I interact with offline would share their last penny with me.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your offline interactions?'
    },
    {
        'text': 'When I feel lonely, there are several people offline I can talk to.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your offline interactions?'
    },
    {
        'text': 'Interacting with people offline makes me interested in things that happen outside of my town.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your offline interactions?'
    },
    {
        'text': 'Interacting with people offline makes me want to try new things.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your offline interactions?'
    },
    {
        'text': 'Talking with people offline makes me curious about other places in the world.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your offline interactions?'
    },
    {
        'text': 'Interacting with people offline makes me feel like part of a larger community.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your offline interactions?'
    },
    {
        'text': 'Interacting with people offline makes me feel connected to the bigger picture.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your offline interactions?'
    },
    {
        'text': 'Interacting with people offline gives me new people to talk to.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your offline interactions?'
    },
    {
        'text': 'There are several people online I trust to help solve my problems.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your online interactions?'
    },
    {
        'text': 'There is someone online I can turn to for advice about making very important decisions.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your online interactions?'
    },
    {
        'text': 'If I needed an emergency loan of $500, I know someone online I could turn to.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your online interactions?'
    },
    {
        'text': 'The people I interact with online would put their reputation on the line for me.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your online interactions?'
    },
    {
        'text': 'The people I interact with online would share their last penny with me.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your online interactions?'
    },
    {
        'text': 'When I feel lonely, there are several people online I can talk to.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your online interactions?'
    },
    {
        'text': 'Interacting with people online makes me interested in things that happen outside of my town.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your online interactions?'
    },
    {
        'text': 'Interacting with people online makes me want to try new things.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your online interactions?'
    },
    {
        'text': 'Talking with people online makes me curious about other places in the world.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your online interactions?'
    },
    {
        'text': 'Interacting with people online makes me feel like part of a larger community.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your online interactions?'
    },
    {
        'text': 'Interacting with people online makes me feel connected to the bigger picture.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your online interactions?'
    },
    {
        'text': 'Interacting with people online gives me new people to talk to.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you agree with the following statements relating to your online interactions?',
    },
    {
        'text': 'Excluding the Zooniverse, how many other online groups, communities and organisations are you an active member of?',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'SC',
        'context': None,
    },
    {
        'text': 'How many offline groups, communities and organisations are you an active member of?',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'SC',
        'context': None,
    },
    {
        'text': 'Most people I know in my offline communities can be trusted.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you say that you agree with the following statements?',
    },
    {
        'text': 'People I know in my offline communities mostly look out for themselves.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you say that you agree with the following statements?',
    },
    {
        'text': 'Most people I know in my online communities can be trusted.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you say that you agree with the following statements?',
    },
    {
        'text': 'People I know in my online communities mostly look out for themselves.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'SC',
        'context': 'To what extent would you say that you agree with the following statements?',
    },
    {
        'text': 'General Science Quiz',
        'kind': 'QU',
        'plot_type': 'Q',
        'category': 'Qu',
        'context': None,
    },
    {
        'text': 'Project Quiz',
        'kind': 'QU',
        'plot_type': 'Q',
        'category': 'Qu',
        'context': None,
    },
    {
        'text': 'Politics Quiz',
        'kind': 'QU',
        'plot_type': 'Q',
        'category': 'Qu',
        'context': None,
    },
    {
        'text': 'I identify my gender as:',
        'kind': 'GN',
        'plot_type': 'P',
        'category': 'In',
        'context': None,
    },
    {
        'text': 'How old were you on your last birthday?',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'In',
        'context': None,
    },
    {
        'text': 'Which of the following best represents your racial or ethnic background?',
        'kind': 'ET',
        'plot_type': 'P',
        'category': 'In',
        'context': None,
    },
    {
        'text': 'Which of the following best describes your current marital or relationship status?',
        'kind': 'YN',
        'plot_type': 'P',
        'category': 'In',
        'context': None,
    },
    {
        'text': 'Under 12 years of age',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'In',
        'context': 'How many children do you have in the following age ranges?',
    },
    {
        'text': '12-17 years of age',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'In',
        'context': 'How many children do you have in the following age ranges?',
    },
    {
        'text': '18 years of age or older',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'In',
        'context': 'How many children do you have in the following age ranges?',
    },
    {
        'text': 'Which of the following best matches your current residential status?',
        'kind': 'YN',
        'plot_type': 'P',
        'category': 'In',
        'context': None,
    },
    {
        'text': 'Which of the following categories best describes your current employment status?',
        'kind': 'YN',
        'plot_type': 'P',
        'category': 'Em',
        'context': None,
    },
    {
        'text': "Approximately how many years have you spent in paid employment during your working life? Enter '0' if not applicable.",
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'Em',
        'context': None,
    },
    {
        'text': 'What is your approximate individual annual income ($) before tax?  Please enter values without commas, spaces etc.',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'Em',
        'context': None,
    },
    {
        'text': 'Yourself -',
        'kind': 'ED',
        'plot_type': 'P',
        'category': 'Ed',
        'context': 'Please indicate the closest match to the highest level of qualification achieved by:',
    },
    {
        'text': 'Either of your parents -',
        'kind': 'ED',
        'plot_type': 'P',
        'category': 'Ed',
        'context': 'Please indicate the closest match to the highest level of qualification achieved by:',
    },
    {
        'text': 'Any scientific qualifications? -',
        'kind': 'YN',
        'plot_type': 'P',
        'category': 'Ed',
        'context': 'Do you have:',
    },
    {
        'text': 'Are these your highest level qualifications? -',
        'kind': 'YN',
        'plot_type': 'P',
        'category': 'Ed',
        'context': 'Do you have:',
    },
    {
        'text': 'Related to science',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'Ti',
        'context': 'Within the last year, how many different extracurricular, evening/weekend or online courses have you taken that are:',
    },
    {
        'text': 'Not related to science',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'Ti',
        'context': 'Within the last year, how many different extracurricular, evening/weekend or online courses have you taken that are:',
    },
    {
        'text': 'Paid Work',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'Ti',
        'context': 'On average, approximately how many hours each week do you spend undertaking the following activities:',
    },
    {
        'text': 'Unpaid Work (Childcare, Housework etc.)',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'Ti',
        'context': 'On average, approximately how many hours each week do you spend undertaking the following activities:',
    },
    {
        'text': 'Leisure',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'Ti',
        'context': 'On average, approximately how many hours each week do you spend undertaking the following activities:',
    },
    {
        'text': 'Volunteering (Excluding Zooniverse)',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'Ti',
        'context': 'On average, approximately how many hours each week do you spend undertaking the following activities:',
    },
    {
        'text': 'Immediate family group',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'FF',
        'context': 'How many people do you consider to be part of your:',
    },
    {
        'text': 'Immediate offline social group',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'FF',
        'context': 'How many people do you consider to be part of your:',
    },
    {
        'text': "Approximately how many friends do you have registered on your Facebook account?   Enter '0' if you do not have an account.",
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'FF',
        'context': None,
    },
    {
        'text': 'Approximately how much money do you typically donate to charity annually ($)?  Please enter values without commas, spaces etc.',
        'kind': 'OP',
        'plot_type': 'H',
        'category': 'Em',
        'context': None,
    },
    {
        'text': 'Which of the following best describes your religious affiliation?',
        'kind': 'YN',
        'plot_type': 'P',
        'category': 'Re',
        'context': None,
    },
    {
        'text': 'Religion is important in my life.',
        'kind': 'AD',
        'plot_type': 'P',
        'category': 'Re',
        'context': 'Please indicate the extent to which you agree with the following statement.',
    },
]

projectLookup = {
    'cancer_cells': 0,
    'moon_zoo': 1,
    'chimp': 2,
    'worms': 3,
    'galaxy_zoo_starburst': 4,
    'serengeti': 5,
    'radio': 6,
    'm83': 7,
    'wisconsin': 8,
    'illustratedlife': 9,
    'milky_way': 10,
    'higgs_hunter': 11,
    'solarstormwatch': 12,
    'chicago': 13,
    'whales': 14,
    'condor': 15,
    'planet_hunter': 16,
    'crater': 17,
    'asteroid': 18,
    'kelp': 19,
    'spacewarp': 20,
    'oldweather': 21,
    'andromeda': 22,
    'cyclone_center': 23,
    'sea_floor': 24,
    'sunspot': 25,
    'notes_from_nature': 26,
    'leaf': 27,
    'planet_four': 28,
    'orchid': 29,
    'penguin': 30,
    'war_diary': 31,
    'wise': 32,
    'galaxy_zoo': 33,
    'ancient_lives': 34,
    'plankton': 35,
    'bat_detective': 36,
}

ethnicityLookup = {
    'White/Caucasian': 'W',
    'Other (please specify)': 'O',
    'Other': 'O',
    'South Asian': 'SA',
    'East Asian': 'EA',
    'Mixed (please specify)': 'M',
    'Mixed': 'M',
    'Hispanic/Latino (of any race)': 'HL',
    'Hispanice/Latino': 'HL',
    'Caribbean': 'C',
    'Middle Eastern': 'ME',
    'Black African': 'BA',
    'Amerindian': 'A',
}
